version: '3.8'

services:
    authenticate:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVICE:  authenticate
        ports:
            - 444:444
        environment:
            PORT: 444

