version: '3.8'

services:
    authenticate:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVICE:  authenticate
        ports:
            - 8080:8080
    profiles:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVICE:  profiles
        ports:
            - 8080:8081
    search:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVICE:  search
        ports:
            - 8080:8082
    upload:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVICE:  upload
        ports:
            - 8080:8082
