version: '3.8'

services:
    authenticate:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVICE:  echoServer
        ports:
            - 443:443
    echo:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                SERVICE:  echoServer
        ports:
            - 8080:8080

