// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package itproject

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ItProjectClient is the client API for ItProject service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ItProjectClient interface {
	Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
}

type itProjectClient struct {
	cc grpc.ClientConnInterface
}

func NewItProjectClient(cc grpc.ClientConnInterface) ItProjectClient {
	return &itProjectClient{cc}
}

func (c *itProjectClient) Hello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/itproject.itProject/Hello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItProjectServer is the server API for ItProject service.
// All implementations must embed UnimplementedItProjectServer
// for forward compatibility
type ItProjectServer interface {
	Hello(context.Context, *HelloRequest) (*HelloResponse, error)
	mustEmbedUnimplementedItProjectServer()
}

// UnimplementedItProjectServer must be embedded to have forward compatible implementations.
type UnimplementedItProjectServer struct {
}

func (*UnimplementedItProjectServer) Hello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Hello not implemented")
}
func (*UnimplementedItProjectServer) mustEmbedUnimplementedItProjectServer() {}

func RegisterItProjectServer(s *grpc.Server, srv ItProjectServer) {
	s.RegisterService(&_ItProject_serviceDesc, srv)
}

func _ItProject_Hello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItProjectServer).Hello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/itproject.itProject/Hello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItProjectServer).Hello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ItProject_serviceDesc = grpc.ServiceDesc{
	ServiceName: "itproject.itProject",
	HandlerType: (*ItProjectServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Hello",
			Handler:    _ItProject_Hello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "itproject/proto/itproject/api.proto",
}
