name: cloud functions deploy

on:
    push:
        branches: [ master ]
        paths: backend/pkg/functions
jobs:
    build:

        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [12.x]

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Setup - gcloud / gsutil
              uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
              with:
                  service_account_key: ${{ secrets.GCLOUD_SERVICE_KEY }}
                  export_default_credentials: true
            - name: Set default project
              run: gcloud config set core/project joshcarp-it-project
            - name: Deploy
              run: |
                  gcloud functions deploy upload \
                         --entry-point=UploadFileFunc \
                         --runtime=go113 \
                         --source=backend/pkg/functions \
                         --trigger-http \
                         --allow-unauthenticated
            - name: Set permissions
              run: |-
                    gcloud config set run/region us-central1 && \
                    gcloud run services add-iam-policy-binding joscarp-it-project \
                      --member="allUsers" \
                      --role="roles/run.invoker" \
                      --platform managed

