name: deploy www
on:
  push:
    branches: [ feature/wysiwyg ]
    paths:
        - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Move frontend dir
        run: mv frontend/* .
      - name: Setup - gcloud / gsutil
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.ACTIONS_SERVICE_ACC }}
          export_default_credentials: true
      - name: Set default project
        run: |
          gcloud config set core/project joshcarp-it-project
          gcloud auth configure-docker
          gcloud config set run/region us-central1
      - name: Build
        run: |-
          gcloud builds submit \
            --quiet \
            --tag "gcr.io/joshcarp-it-project/www:$GITHUB_SHA"
      - name: Deploy
        run: |-
          gcloud run deploy "www" \
            --quiet \
            --region "us-central1" \
            --image "gcr.io/joshcarp-it-project/www:$GITHUB_SHA" \
            --platform "managed" \
            --allow-unauthenticated
      - name: Set permissions
        run: |-
          gcloud run services add-iam-policy-binding www \
            --member="allUsers" \
            --role="roles/run.invoker" \
            --platform managed

