name: Docs
on:
    push:
        branches: [ feature/doc-generation ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: it-project.wiki
      - name: Checkout
        uses: actions/checkout@v2
        with:
           path: it-project
      - name: Gen Docs
        working-directory: it-project
        run: |
          make docs
          mkdir -p ./it-project.wiki/service-documentation
          mv docs ../it-project.wiki/service-documentation
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          working-directory: it-project.wiki
          github_token: ${{ secrets.GITHUB_TOKEN }}