name: Docs
on:
    push:
        branches: [ feature/doc-generation ]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: {{ secrets.GITHUB_TOKEN }}
          path: it-project.wiki
      - name: Checkout
        uses: actions/checkout@v2
        with:
           path: it-project
      - name: Gen Docs
        working-directory: it-project
        run: |
          make docs
          mv docs ../it-project.wiki/service\ documentation
      - name: push
        working-directory: it-project.wiki
        run: |
          git add -A && git commit -m "Update autogeneration" && git push